### ISSUE TITLE
editing

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/swtr#16]
before publishing annotation, i tried editing it in firefox 30.0 and google chrome 32.0, but as soon as i select edit icon which is pen annotation box disappears. i cleared cash also. So i am not able to edit annotation.

**Comment by ecthiender** [comment]
Not enough information. Is this error reproducible?

**Comment by Amrapalivishwa** [comment]
Earlier we could edit annotation after saving and  before publishing now ' edit ' does not work. Try to edit any  annotation  after saving and  before publishing you will get the idea.
