### ISSUE TITLE
Oops! Seems like the image URL is wrong! Or we couldn't fetch the image.

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/swtr#4]
Oops! Seems like the image URL is wrong! Or we couldn't fetch the image.
http://static.moralstories.org/wp-content/uploads/2011/07/famer.jpg
http://static.moralstories.org/wp-content/uploads/2013/09/bearnfriend.jpg

**Comment by ecthiender** [comment]
These images have permission issues. If you directly paste that link in the browser, then it works. But if you try to access the image from some other website or app it does not work.
So we cannot really do anything in this regard.

We are working on a tool which will combine image and text annotation. So that when you are browsing a website you can annotate text and images of that page. There will be no need to get the link to the image and use it separately for image annotation. When this tool is ready, it will hopefully solve the problem.

**Comment by Amrapalivishwa** [comment]
earlier when i was doing copy past from news paper web page  it used to
work in swtr, it is only last two weeks, This problem has occured.

**Comment by Amrapalivishwa** [comment]
today i tried image which earlier used to give message "
Oops! Seems like the image URL is wrong! Or we couldn't fetch the image"

today also it gave the same massage then i pressed back arrow to go back to
previous page than

fresh page appeared without message which says" Enter the URL of an image
or web page below, and start annotating!"

than i pasted the link
http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Odissi_Perfomance_DS.jpg/370px-Odissi_Perfomance_DS.jpg

which was not working earlier now worked. So i think when above message
comes after that whatever link i try for all the images it gives same
message, but when this message comes, if i press back arrow and go to
previous page, and paste link, than it works so, if tool gives message that
"press back arrow to annotate other image",  When above message comes then
it will work.

On Fri, Aug 22, 2014 at 2:33 PM, Amrapali Vishwanath <amrapali@servelots.com

**Comment by arvindkhadri** [comment]
I can't reproduce the error you are talking about.  The image annotation
app at http://testapp.swtr.us does not throw any error when I load the
application with this
http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Odissi_Perfomance_DS.jpg/370px-Odissi_Perfomance_DS.jpg,
URL.

To fix your issue, clear your cache and reload.  If the problem persists,
please open a new bug.  The bug reported first and the issue you are facing
right now are not the same.

**Comment by Amrapalivishwa** [comment]
i wrote en email why i was facing problem, if  i press back arrow and paste
url it works
