### ISSUE TITLE
post - log out

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/swtr#7]
After annotating first image i could not annotate other images so to test i logged out of  Sweet store, Even after i logged out of sweet store and reloaded sweet maker app, it still said ‘you are signed in as Amrapali”

**Comment by ecthiender** [comment]
The swt maker app is tied to the swt store in cases of authenticating a user (that is, logging in), posting a swt to the store etc.

But it is totally independent in cases of maintaining session for a user etc.

So it does not matter if you logged out of swt store. As long the swt maker app maintains your session, you will be logged in.
