### ISSUE TITLE
sweet button

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/swtr#8]
http://qph.is.quoracdn.net/main-qimg-78a6e581c55ad750e69ef007dfdedfd8?convert_to_webp=true
i did narration for above post and clicked white color ‘sweet’ button before sweeting again i clicked white color  ‘sweet’ button again so annotation 
appeared twice in a box than i confirmed to sweet(second ‘sweet’ button  which is in a box ‘blue color) so annotation got posted twice. once in a box only second sweet should be active and first one should be inactive. i have explained this to arvind.

**Comment by ecthiender** [comment]
This is fixed I think.
